### ISSUE TITLE
It has a virus!!!

### ISSUE THREAD

**Issue by davidredondo0** [jonnytest1/minikeyboard#2]
Hi there, I just scanned the file with virustotal tool and it said that it has malware inside. Therefore, be careful installing the sofware. I recommend using a virtual machine to set it up.

**Comment by jonnytest1** [comment]
🤔 what kind of malware

**Comment by jonnytest1** [comment]
https://www.virustotal.com/gui/file/4ae53d3a40921e4f57444c489fa1b38fe91a2e907feda17630450fc97a7cd7b1
🤔 considering all the top known antivirus scanners say its good i think the 2 flagged ones are probably a false positive
i googled for the specific detection and according to reddit the detection is "shady" 
https://www.reddit.com/r/antivirus/comments/wlkud8/trojanmalware300983susgen_false_positive/

and its not like the use case of manual usb programming isnt in any way borderline suspicious ^^
but using it in a vm definitely doesnt hurt 😌

**Comment by jonnytest1** [comment]
https://github.com/jonnytest1/minikeyboard/commit/120b317da9cbf9aac9d974c308b839c5955c336e updated readme

**Comment by davidredondo0** [comment]
The same you found. It seems harmless taking into account the info you provide, but i'd rather like to use a vm to make sure hahahaa. Thanks for updating the readme !!
